baseURL = "/"
publishDir = "../../dist"
title = "David Morton Portfolio"

[params]
  summary = "David Morton is a writer, journalist and web developer from Chattanooga, Tennessee."

[author]
  name = "David Morton"
  email = "michaeldavidmorton@gmail.com"

[taxonomies]
  contribution = "contributions"
  tool = "tools"

[related]
  threshold = 100
  includeNewer = true
  toLower = false
  [[related.indices]]
    name = "contributions"
    weight = 100
  [[related.indices]]
    name = "tools"
    weight = 10
